### ISSUE TITLE
Umfeldsuche (Postleitzahl)

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#10]
Nur Ergebnisse aus der Umgebung der übergebenen Postleitzahl sollen zurückgegeben werden.

Optimalerweise wird die Distanz mit zurückgegeben, sodass die Suchergebnisse entsprechend der Distanz sortiert werden können.

**Comment by MaxWies** [comment]
Dabei sollten wir aber nicht die Postleitzahl nehmen sondern die Koordinaten, die wir mindestens aus der Postleizahl erhalten. Es gibt sicherlich einen Lösungsweg Distanzen zwischen den Koordinaten zu berechnen, sodass man alle Ergebnisse in einem gewissen Umkreis (z.B. 50km) erhält.

**Comment by chaoran-chen** [comment]
Klingt gut. Willst du es implementieren?
