### ISSUE TITLE
BCC versandten Emails an eigene Adresse

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#12]
Kopien aller verschickten Emails sollen (im eigenen Emailfach) gespeichert werden.

**Comment by chaoran-chen** [comment]
Bitte einen Issue erst schließen, nachdem die Implementierung reviewt und in den Master gemergt wurde.

**Comment by MaxWies** [comment]
@Aqibansari Ich habe neue Funktionen in dem MailService implementiert für das Issue #31 . Kannst du den Master in deinen Branch mergen und dann die BCC Funktion auch für die Methode sendDemandMailToProvider implementieren? Es gibt inzwischen die Methode sendMail. Du könntest sie erweitern, dass man zwischen BCC und nicht BCC unterscheidet.

**Comment by chaoran-chen** [comment]
Ich übernehme das mal.
