### ISSUE TITLE
Remove postalcode field of resources

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#127]
It is enough that an offer has one address. For the resources, there is no need to enter another postal code again. Therefore, the postal code field of the three resources should be completely removed.

**Comment by MaxWies** [comment]
So resources in the offer share all the same postalcode which is given within the provider object?

**Comment by chaoran-chen** [comment]
Yes.

**Comment by MaxWies** [comment]
But the provider might have resources located at another location? For me this makes our service more limited. Do you have some reasons for this?

**Comment by chaoran-chen** [comment]
Well, we expect that the provider will be in close proximity to the resource. And as we have seen in the case of the registered helpers, in most cases, the helpers enter their information themselves.

The main reason for changing it is that we are going to have major changes to the address systems. The required information to identify a location should be configurable for each region. It might be the case that some regions don't have postal code at all. It would make things a lot simpler if there are not so many places where we have an address.

**Comment by MaxWies** [comment]
Alright. This also affects our database. `device`, `consumable `and `personal ` won't have a corresponding address anymore, am I right?

**Comment by chaoran-chen** [comment]
Correct
