### ISSUE TITLE
Kontaktdaten anonymisieren

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#13]
Backend für https://github.com/COVID19-PIRAT/frontend/issues/66

Vorschlag:

Ändere: `POST /resources`

```
Request Body:
    - provider erhält weiteres Attribut: ispublic (boolean)
```

Ändere: `GET /resources/*`

```
Response Body
    - Ist ispublic==true, wird provider nicht zurückgegeben
    - Jedes Resource Element erhält eine ID. Diese wird stets zurückgegeben. D.h.:
        [{ "resource": { id: ... } }]
```

**Comment by MaxWies** [comment]
Anstatt publicData würde ich ispublic besser finden. -> keine Großbuchstaben wegen Postgres und public am Anfang ist nervig beim coden.

**Comment by MaxWies** [comment]
@chaoran-chen Kannst du daraus zwei Issues machen? Einen eigenen Issue für POST /resources/consumables|devices|manpower/{id}/contact

Dann kann ich für den anderen einen Pull Request starten.

**Comment by chaoran-chen** [comment]
okay!
