### ISSUE TITLE
Angebotserstellung Bestätigungsmail bearbeiten

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#17]
Die Bestätigungsemail, dass man ein Angebot erstellt hat, soll alle Angaben (Kontaktdaten sowie die Ressourcen) beinhalten.

Außerdem Sprache prüfen, u.a. Duzen vs. Siezen.

**Comment by chaoran-chen** [comment]
"Unter diesem LinkEntity können Sie Ihr Angebot einsehen und bearbeiten"

LinkEntity????

**Comment by chaoran-chen** [comment]
Siehe https://github.com/COVID19-PIRAT/Konzept/issues/42 !

**Comment by MaxWies** [comment]
#42 -> Das sind doch keine Mails die das Backend verschicken soll?

**Comment by chaoran-chen** [comment]
Nach d63df3fbe8385ac68f84c369f2a56ecc8e272a9d erstmal erledigt.
