### ISSUE TITLE
Weitere Emailkonfigurationen aus dem Code nehmen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#19]
Aktuell sind die Daten des GMail-Servers fest im Code. Sie müssen raus und auch über Umgebungsvariablen gesetzt werden.

**Comment by MaxWies** [comment]
Du meinst gmail host und gmail port?

**Comment by chaoran-chen** [comment]
Post/Protokoll kannst du bei SSL lassen, host muss konfigurierbar sein.
