### ISSUE TITLE
Umgebungsvariablen beim Serverstart prüfen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#20]
Beim Starten des Servers soll geprüft werden, ob alle notwendigen Umgebungsvariablen gesetzt sind. Falls nicht, soll der Server sich direkt wieder abschalten.

**Comment by MaxWies** [comment]
Für den Beginn reicht es dies in der Startup.cs zu tun.

Dafür dort eine private Method anlegen, die die Environment Variablen  die es gibt checkt. Bei nicht vorhanden sein einer, kann das Backend nicht starten.

Das Checken entweder hard gecodet oder durch Einlesen eines Ressource Files in dem die Namen der Variablen stehen. Aber natürlich nur die Namen der Variablen, nicht die Werte!! ;)
