### ISSUE TITLE
Datenbank für Entwicklung

### ISSUE THREAD

**Issue by MaxWies** [COVID19-PIRAT/backend#21]
Derzeit arbeiten wir auf einer DB für Entwicklung als auch für Production. Durch die Entwicklung erzeugen wir "schlechte" Daten und für die Entwicklung werden die Tabellen der DB modifiziert.

Wir sollten eine zweite DB haben für die Entwicklung haben.

Name der Environment Variable für Connection String: **PIRAT_CONNECTION_DEV**

Dar Connection String hängt dann davon ab, ob das Backend lokal oder prod gestartet wird.

**Comment by chaoran-chen** [comment]
Wir könnten doch weiterhin nur PIRAT_CONNECTION nutzen und für den Server online werde ich eine neue DB anlegen.

Allerdings wäre es dann wichtig, dass die DDL für die Datenbank stets dokumentiert wird, damit ich entsprechende Änderungen durchführen kann.

**Comment by MaxWies** [comment]
Und wo wird unterschieden, wo die Daten hinkommen bzw. abgerufen werden?

**Comment by chaoran-chen** [comment]
Lokal wird immer die Entwicklungsdatenbank benutzt. Auf dem Server immer die Production-DB

**Comment by MaxWies** [comment]
Alles klar!

**Comment by chaoran-chen** [comment]
Die DB für den Server muss ich dann noch anlegen. Daher lasse ich den Issue hier nochmal offen und assigne es mir.

**Comment by chaoran-chen** [comment]
Es gibt nun eine Datenbank für die offizielle Version und eine Datenbank für die Testseite.
