### ISSUE TITLE
Provider Element nicht wiederverwenden

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#30]
Zurzeit ist es so, dass die Daten eines Providers, der zweimal separat ein Angebot reinstellt, nur einmal gespeichert wird. (Ich vermute, dass es über die Emailadressse geprüft wird.) Dies ist ein Problem aus zwei Gründen.

Zum einen ist es unintuitiv. Z.B. könnte jemand beim zweiten Eintragen eine andere Telefonnummer nutzen wollen und wird sich wundern, weshalb danach in der Übersicht was anderes steht, als er eingegeben hat.

Zum anderen ist es eine Sicherheitslücke! Angriffsszenario: Ein Anbieter (im Folgenden als Opfer bezeichnet) trägt alle seine persönlichen Daten ein und wählt aus, dass diese nicht veröffentlicht werden dürfen. Der Angreifer kennt nur den Namen und die Email des Opfers und erstellt ein Angebot mit diesen Daten. Daraufhin wird er zu der Angebot bearbeiten/Angebotübersichtseite weitergeleitet, auf der der Angreifer alle anderen Daten des Opfers einsehen kann.

Bug initial gemeldet von @Julia91457 

@MaxWies, bitte kommentieren :)

**Comment by MaxWies** [comment]
Also für jedes Offer einen eigenen Provider?

Die Provider in Resourcen Rückgaben "mergen" wenn Provider Daten identisch und ispublic gleich?

**Comment by chaoran-chen** [comment]
Für jedes Offer einen eigenen Provider finde ich besser. Vielleicht kann man ja eine `Offer` Tabelle anlegen, die `link` und `provider` zusammenführt?
