### ISSUE TITLE
Production Modus

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#35]
Wie kann man den Server so starten, dass es z.B. Swagger nicht einbindet? Was gibt es sonst noch zu beachten?

**Comment by mrkrizic** [comment]
In Startup.cs (Line 106) wird die methode app.UseSwagger bzw app.useSwaggerUI aufgerufen. Falls hier die Reihenfolge der app.Use[Component] irrelevant ist, sollte es genügen die beiden Swaggerkomponenten in der if(env.isDevelopment) überprüfung (Line 80) aufzurufen.

**Comment by MaxWies** [comment]
Genau, über env.IsDevelopment bzw. env.IsProduction kann man den Modus prüfen. In Prduction sollen die Swagger Komponente nicht hinzugefügt werden.

**Comment by chaoran-chen** [comment]
Gibt's noch mehr zu tun oder ist das alles und dies kann zu?

**Comment by MaxWies** [comment]
Wenn du kein Swagger mehr hast in Production auf dem Server, dann schließe es
