### ISSUE TITLE
CI/CD mit Github Actions und Docker

### ISSUE THREAD

**Issue by MaxWies** [COVID19-PIRAT/backend#45]
Aufbau der CI/CD Umgebung

**Comment by chaoran-chen** [comment]
Muss es Travis sein? Wir verwenden aktuell Github Actions und es funktioniert ganz gut. Vielleicht kann @bieniusa hierbei mithelfen?

**Comment by bieniusa** [comment]
Travis brauchen wir nicht mehr, da Github Actions das gleiche leistet.
