### ISSUE TITLE
"Neue Angebote erschienen"-Email: Details

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#52]
In den bei neuen Angeboten täglich versandten Emails an Leute, die eine Region abonniert haben, sollten auch direkt stehen, in welchen Kategorien nun neue Ressourcen zur Verfügung stehen.

**Comment by mrkrizic** [comment]
Ich sollte noch heute fertig werden. Verschiedene Kategorien sind noch nicht getestet worden und die Summe der neuen Angebote sollte vermutlich ebenfalls angegeben werden.

**Comment by chaoran-chen** [comment]
Alles klar, dankeschön! :)
