### ISSUE TITLE
Konfigurierbarkeit der Kategorien

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#79]
Die Kategorien von Geräten und Verbrauchsmaterialien sollen ohne Änderung von Code zu konfigurieren sein. Das heißt, dass diese verfügbaren Kategorien (inkl. ihre Bezeichnungen in den verschiedenen Sprachen) durch das Backend verwaltet und beim Aufruf der Webapp von diese angefordert werden müssen.

Die Kategorien können wahlweise in der Datenbank oder in Konfigurationsdateien des Backends abgespeichert werden. Ich bevorzuge Konfigurationsdateien.

**Comment by Timo-Weike** [comment]
Ich könnte dass morgen angehen und vermutlich auch fertig machen. Am einfachsten wäre es vermutlich die als eine odere mehrere Dateien (eine für jede Sprache) abzulegen und die während des StartUps zu laden, parsen und dann im speicher zu halten.

Wie soll dann die neue route für die liste mit allen Kategorien ausehen?
`/categories`

könnte eine liste mit den internen Bezeichnern wieder geben und

`/categories/{lang}`
könnte eine liste mit Tupel die aus den internen Bezeichnern und dem in der jeweiligen Sprache wieder geben.

**Comment by chaoran-chen** [comment]
Ich würde es möglichst einfach halten. Vielleicht könnte man eine Route `/startup` erstellen, die das Frontend beim Start aufruft, um alles, was es braucht, auf einmal zu bekommen?

**Comment by MaxWies** [comment]
Dann würden wir bei `/startup` alles fetchen? Also Kategorien für jedes Land? Die Idee ist ja länderspezifisch die zugehörige Konfig Datei vom Backend zu holen.

**Comment by MaxWies** [comment]
Ich finde wir sollten `/categories `und `/categories/{lang}` nehmen, da sonst ein Startup Controller sehr groß werden könnte, wenn in den nächsten Wochen der erweitert wird. Unser 'ResourceController' ist ja bereits auf gutem Wegen ein Bloated Controller zu werden.

Allerdings würde ich anstatt `/categories/{lang}` `/categories/{nation}` vorschlagen, da die Idee war Konfigurationsdateien für die jeweiligen Länder zu erstellen.

**Comment by chaoran-chen** [comment]
Stimmt, es sollte aber längerspezifisch sein. Dann vielleicht `/startup/{country}` für die gesamte Konfiguration eines Landes?

**Comment by Timo-Weike** [comment]
Meine Idee mit `/categories/{lang}` war halt auch dass so sich das front end einfach eine Liste mit den verfügbaren Kategorien holen kann um dann sowas wie eine ComboBox für einen Fiilter oder andere Formulare zu füllen.

Dass sich der Client über eine `/startup/{country}` route eine gesamt Konfiguration holt finde ich für nicht nötig, aber ich weiß auch nicht wie dass im frontend geregelt ist.

Und mit `{lang}` meinte ich dann so ein Tag wie es für die [`CultureInfo`][1] Klasse benutzt wird.
Da wäre halt `en-us` zum beispiel der Englische _"Dialekt"_  wie er in den USA gesprochen wird. Und wenn wir nicht so viel aufschlüsselung machen wollen, dann sollten wir die Bezeichnungen nach Sprachen Kategorisieren und nicht nach Ländern oder Regionen. 

Weil was ist zum Beispiel wenn wir noch Spanisch aufnehmen, denn nicht jeder in spanien kann Spanisch. Da wäre zum Beispiel `es-es` das Spanisch aus Spanien und `ca-es` das Catalan was in Spanien gesprochen wird. Also `Lang-Region` und da die Region aufdröselung momentan vermutlich ohnehin nicht nöti ist würde ich für `/categories/{lang}` sein.


 [1]: https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.createspecificculture?view=netframework-4.8

**Comment by Timo-Weike** [comment]
Also mein Konkreter vorschlag ist eigentlich nur die folgenden abfragen zu ermöglichen

 * `/categories` liste mit den interen Bezeichnern
* `/categories/de` liste mit `(interner Bezeichner, deutschsprachiger Bezeichner)`
* `/categories/en` liste mit `(interner Bezeichner, englischsprachigem Bezeichner)`
* `/categories/it` liste mit `(interner Bezeichner, italienischsprachigem Bezeichner)`

**Comment by chaoran-chen** [comment]
Es gibt allerdings Kategorien für unterschiedliche Ressourcen, es gäbe also eine Liste von Kategorien für Geräte und eine für Verbrauchsgüter am Anfang. Wenn wir irgendwann dann noch die verfügbaren Einheiten, Fachgebiete und Qualifikationen konfigurierbar machen wollen, müsste das Frontend beim Starten erstmal fünf Anfragen stellen?

Es gibt für uns einen Unterschied zwischen Land und Sprache. Jedes Land wird eine andere Konfiguration bekommen. Die Länder haben nicht nur unterschiedliche Sprachen, sondern auch unterschiedliche Kategorien und in manchen Ländern wird man Personal anbieten dürfen, in anderen vielleicht nicht.

**Comment by chaoran-chen** [comment]
Als Kompromiss vielleicht `/configuration/{country}/{lang}` ?

**Comment by Timo-Weike** [comment]
`/.../{country}/{lang}` finde ich gut.

> Wenn wir irgendwann dann noch die verfügbaren Einheiten, Fachgebiete und Qualifikationen konfigurierbar machen wollen, müsste das Frontend beim Starten erstmal fünf Anfragen stellen?


Aber wird dass denn alles auf einmal gebraucht? Weil wenn ja würde ich dir zustimmen.

**Comment by chaoran-chen** [comment]
Ja, die Daten werden sehr oft alle gebraucht. Wenn man z.B. eine Angebotsübersicht aufmacht, hat man ja alles auf einmal.

**Comment by Timo-Weike** [comment]
@chaoran-chen @MaxWies ich habe mal einen entwurf für eine config datei erstellt, guckt euch die mal bitte an und sagt was ihr davon haltet

https://github.com/COVID19-PIRAT/backend/blob/648918b19ed644f187f1e9596a499d74e8d79dd0/Pirat/Configuration/region_config.xml#L1-L21

**Comment by chaoran-chen** [comment]
XML? :/ Können wir nicht lieber YAML (oder JSON) nutzen?

**Comment by chaoran-chen** [comment]
Und ich würde eher pro Region eine eigene Konfiguration erstellen, z.B. `backend/Pirat/Configuration/config.{region}...`

**Comment by Timo-Weike** [comment]
Wie wäre es dann mit dateien wie
`config.cat.{type}.json` als List für alle Kategorien die zum Beispiel ein Consumable hat.
und dann `config.cat.{region}.json` für als liste für die Kategorien die in der jeweiligen Region verfügbar sind (mit lokaliserem Namen)

Also z.B.:

```
config.cat.consumable.json
-------
[
"MASKE",
"SCHUTZKLEIDUNG",
...
]
```

und dann 
```
config.cat.de-DE.json
-------
{
  "MASKE" : "Maske",
  "SCHUTZKLEIDUNG": "Schutzkleidung"
}
```

```
config.cat.en-UK.json
-------
{
  "MASKE" : "Face mask",
  "SCHUTZKLEIDUNG": "Protective suit"
}
```

**Comment by chaoran-chen** [comment]
Okay!

Kannst du mir bitte aber nochmal erläutern, wie die Regionsbezeichnung zu lesen ist? Wie würde man die englische Version der deutschen Plattform nennen? `en-DE`?

**Comment by chaoran-chen** [comment]
Um trotzdem nochmal einen Gegenvorschlag zu unterbreiten:

```
config.de.json
-------
{
  "languages": ["de", "en"],
  "categories": {
    "device": [
      "PCR_THERMOCYCLER",
      "VORTEXTER"
    ],
    "consumable": [
      // ...
    ],
    // Später potentiell auch "personnelQualification", "personnelArea" und "consumableUnit"
  },
  "labels": {
    "de": {
      "MASK": "Maske",
      "PCR_THERMOCYCLER": "PCR Thermocycler"
    }
  }
}
```



Noch anschaulicher fände ich YAML:

```
config.de.yaml
-------
languages:
  - de
  - en
categories:
  - device:
    - PCR_THERMOCYCLER
    - VORTEXTER
  - consumable
    ...
labels:
  - de:
      MASK: MASKE
      PCR_THERMOCYCLER: PCR Thermocycler
  - en:
      ...
```

**Comment by Timo-Weike** [comment]
Also wenn wir für die Deutsche Region auch eine Englisch Sprachige version anbieten wollen dann würde ich dass vorhanden sein von Kategorieren in den verschiedenen Regione vom Datei-Layout von den Übersetzungen in die verschiedenen Sprachen von einander trennen. Sonst hat man hinterher zigstellen wo man die englischen Bezeichnungen anpassen muss

```
config.de.json 
------
{
  "languages": [ "de", "en" ],
  "categories": {
    "device": [
      "PCR_THERMOCYCLER",
      "VORTEXTER",
      ...
    ],
    "consumable": [
      // ...
    ]
  }
}
```
und
```
config.at.json // für Österreich
-----
{
  "languages": [ "de", "en" ],
  "categories": {
    "device": [
      "PCR_THERMOCYCLER",
      "VORTEXTER",
      ...
    ],
    "consumable": [
      // ...
    ]
  }
}
```

und dann halt noch
```
config.lang.de.json
-----
{
  "consumable": {
    "MASKE": "Maske",
    "SCHUTZKLEIDUNG": "Schutzkleidung",
    ...
  },
  "devices": {
    "PCR_THERMOCYCLER": "PCR Thermocycler",
    "RT_PCR_THERMOCYCLER": "Real-Time PCR Thermocycler",
    ...
  }
}
```
und noch
```
config.lang.en.json
-----
{
  "consumable": {
    "MASKE": "Face mask",
    "SCHUTZKLEIDUNG": "Protective suit",
    ...
  },
  "device": {
    "PCR_THERMOCYCLER": "PCR thermal cycler",
    "RT_PCR_THERMOCYCLER": "Real-Time PCR  thermal cycler",
    ...
  }
}
```

Gerne auch als yaml, hättest du da schon eine ParseLib im Auge?

**Comment by Timo-Weike** [comment]
Und welche Regions und Sprach Kombinationen unterstützen wir den bisher?

**Comment by chaoran-chen** [comment]
okay, so können wir das machen.

Noch unterstützen wir nur Deutschland, dieser Issue hier ist eine wichtige Grundlage, um das Tool für andere Länder anbieten zu können. Wir haben bereits ein Österreichteam und Italien, UK, Australien (und evtl. Schweiz) sind in Arbeit.

**Comment by Timo-Weike** [comment]
Habe gerade einen zweiten Draft gepushed, könnt ihr euch gerne mal angucken und was zu sagen

**Comment by Timo-Weike** [comment]
@chaoran-chen und @MaxWies es sollte auch noch überlegt werden wie die nun über den ConfigurationService lokaliserten Kategorie bezeichnungen beim SubscriptionService integriert werden. 
Weil um die Mail in der vom Empfänger gewünschten Sprache zu erstellen müsste die Subscription am besten noch irgendwie eine Region und Sprache zugeordnet bekommen.

Es gibt ja die Klasse `RegionSubscription`, wie ist deren Semantik zu verstehen? Soll ich für z.B. für alle in Deutschland Angebotenen "Dinge" eine Benachrichtigung erhalten?

**Comment by chaoran-chen** [comment]
Ich schaue da später mal rein, danke für den Hinweis!
