### ISSUE TITLE
Import von Bedarfslisten

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#84]
CSV Listen mit nachgefragten Ressourcen sollen **durch uns (nicht durch die Nutzer!)** importiert werden.

Wie machen wir das am besten? Schreiben wir ein separates Programm / Skript oder wird es ein Teil des ASP.NET Servers?

**Comment by Timo-Weike** [comment]
Ich würde dass schon über die API machen, gibt es sowas wie eine Admin-Seite auf der Website?

**Comment by chaoran-chen** [comment]
Noch nicht, aber eine ganz rudimentäre Adminseite kann man bestimmt schnell aufsetzen. Dann brauchen wir aber auch ein Authentifikationssystem im Backend, was meinst du, wie schnell wir das implementieren können?

**Comment by chaoran-chen** [comment]
Wie Timo vorgeschlagen, werde ich jetzt eine kleine Adminseite bauen. Tatsächlich werde ich sogar die gesamte CSV-Parselogik in das Frontend verschieben. Im Backend wird also nur ein einfacher Endpoint zum Erstellen von Bedarfsanfragen gestellt. Der Endpoint wird anfangs mit einem einfachen `adminToken` gesichert, aber wenn wir später einführen, dass jeder direkt auf der Webseite ihren Bedarf hochladen bzw. eintragen dürfen, können wir die Sicherung einfach entfernen und die API weiternutzen.

Die API ist sehr ähnlich zu `POST /resources`.

Neu: `POST /demands`

**Request body:**

```
{
    adminToken: string,
    provider: Provider,
    consumables: Array<Consumable>,
    devices: Array<Device>
}
```

Provider:

```
{
    name (required): string,
    organisation (required): string,
    phone: string,
    mail (required): string,
    address: Address
}
```

Consumable:

```
{
    category (required): string,
    name: string,
    manufacturer: string,
    amount (required): int,
    unit (required): string,
    annotation: string
}
```

Device:

```
{
    category (required): string,
    name: string,
    manufacturer: string,
    amount (required): int,
    annotation: string
}
```

**Comment by MaxWies** [comment]
Ein Vorschlag zum AdminKey. Da dieser für die Authentifizierung ist sollten wir stattdessen ein x-api-key nehmen, der im Header steht. Eine Middleware Komponente kann dann diesen prüfen.

**Comment by chaoran-chen** [comment]
Irgendwann bauen wir eine vernünftige Authentifikation, aber nicht bis Montagabend ;)
