### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#90]
Die README.md soll aktualisiert werden.

**Comment by chaoran-chen** [comment]
Who wants to take this? @MaxWies, @Timo-Weike, @dhach ?

**Comment by Timo-Weike** [comment]
To what should it be updated? Please be more clear how what should be added/removed/reworked.

**Comment by chaoran-chen** [comment]
See https://www.notion.so/pirattool/backend-0db5c46ac2ec4255870a1376ff78f99e
