### ISSUE TITLE
Neuer Endpoint: Angefragte Ressourcen zurückgeben

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#93]
https://github.com/COVID19-PIRAT/frontend/issues/133 braucht eine entsprechende API.

**Vorschlag:**

`GET /demands/device|consumable/search`

Verpflichtender Queryparameter: `category`

Optionale Queryparameter: (`country` + `postalcode`) und `kilometer`.

Standardmäßig herrscht keine Distanzeinschränkung.

**Comment by MaxWies** [comment]
Wenn `postalcode` dabei ist, ist auch immer `country` dabei, oder?

**Comment by chaoran-chen** [comment]
Oh ja, na klar!

**Comment by chaoran-chen** [comment]
Oder bisschen anders: als Vorbereitung auf die Internationalisierung soll `country` verpflichtend sein.

**Comment by MaxWies** [comment]
Okay, aber unseren `AddressMaker `können wir nur von der Leine lassen, wenn der `postalcode `dabei ist.

**Comment by chaoran-chen** [comment]
okay, dann machen wir es erstmal wieder mit postalcode+country im Verbund. Für die Internationalisierung überlegen wir uns was neues.

**Comment by MaxWies** [comment]
Mmh, vielleicht reicht nur country beim Erstellen der Koordinaten. Das müsste man nochmal testen.

**Comment by chaoran-chen** [comment]
Nein, darum geht es eigentlich gar nicht. Das Land wird später auf einer ganz anderen Art und Weise verwendet, da aktuell kein zwischenstaatlicher Austausch anforciert wird. Zwei Städte mögen zwei km voneinander entfernt liegen, wenn eine Grenze dazwischen ist, wird der Austausch deutlich schwieriger.
