### ISSUE TITLE
Admin key API

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/backend#95]
Eine API, die einen Admin-Key validiert, soll erstellt werden.

```
POST /admin/verify-key

Query body:
{
    "adminKey": string
}

Return:
{
    "success": boolean
}
```

Der Admin-Key ist fix und wird über eine Umgebungsvariable eingelesen.

**Comment by MaxWies** [comment]
Mit einer Middlewarekomponente, die sich den adminkey anschaut, bräuchtest du keinen POST und keine API.

**Comment by chaoran-chen** [comment]
Eine separate API bräuchte ich trotzdem, denn die Seite funktioniert so, dass man zuerst den Key eintippen muss - sich also einloggt, und erst danach zu der Seite weitergeleitet wird, auf der man Bedarf importieren kann.
